###
POST http://localhost:4004/shop/Orders HTTP/1.1
content-type: application/json

{
    "customer": "Andreas Müller",
    "items": [
        {
            "product": "Oisters",
            "quantity": 25
        },
        {
            "product": "Water"
        },
        {
            "product": "Beer",
            "quantity": 50
        }
    ]
}

###

POST http://localhost:4004/shop/Orders HTTP/1.1
content-type: application/json

{
    "customer": "Peter Fischer",
    "items": [
        {
            "product": "Oil Canister"
        },
        {
            "product": "Butter",
            "quantity": 18
        },
        {
            "product": "Shotgun",
            "quantity": 3
        }
    ]
}